
artifacts_root: artifacts

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/Electricity_bill.parquet
  val_status: artifacts/data_validation/validation_status.json
  critical_columns:
    - 'Fan'
    - 'Refrigerator'
    - 'AirConditioner'
    - 'Television'
    - 'Month'
    - 'MonthlyHours'
    - 'TariffRate'
    - 'ElectricityBill'
    - 'TotalApplianceHours'
    - 'City_Chennai'
    - 'City_Dahej'
    - 'City_Faridabad'
    - 'City_Gurgaon'
    - 'City_Hyderabad'
    - 'City_Kolkata'
    - 'City_Mumbai'
    - 'City_Nagpur'
    - 'City_Navi Mumbai'
    - 'City_New Delhi'
    - 'City_Noida'
    - 'City_Pune'
    - 'City_Ratnagiri'
    - 'City_Shimla'
    - 'City_Vadodara'
    - '5Company_Bonfiglioli Transmission Pvt. Ltd.'
    - 'Company_CESC'
    - 'Company_GE T&D India Limited' 
    - 'Company_Guj Ind Power'
    - 'Company_Indowind Energy' 
    - 'Company_JSW Energy Ltd.'
    - 'Company_Jaiprakash Power' 
    - 'Company_Jyoti Structure'
    - 'Company_KEC International' 
    - 'Company_Kalpataru Power'
    - 'Company_L&T Transmission & Distribution'
    - 'Company_Maha Transco – Maharashtra State Electricity Transmission Co, Ltd.'
    - 'Company_NHPC' 
    - 'Company_NLC India' 
    - 'Company_NTPC Pvt. Ltd.'
    - 'Company_Neueon Towers / Sujana Towers Ltd.'
    - 'Company_Optibelt Power Transmission India Private Limited'
    - 'Company_Orient Green'
    - 'Company_Power Grid Corp'
    - 'Company_Ratnagiri Gas and Power Pvt. Ltd. (RGPPL)'
    - 'Company_Reliance Energy' 
    - 'Company_Reliance Power'
    - 'Company_Ringfeder Power Transmission India Pvt. Ltd.'
    - 'Company_SJVN Ltd.' 
    - 'Company_Sterlite Power Transmission Ltd'
    - 'Company_Sunil Hitech Eng' 
    - 'Company_Tata Power Company Ltd.'
    - 'Company_Torrent Power Ltd.'
    - 'Company_Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.'
    - 'Company_TransRail Lighting' 
    - 'Company_Unitech Power Transmission Ltd.'
    - 'Company_nan'
    - 'season_Summer'
    - 'season_Winter'
    - 'season_nan'
    - 'UsageCategory_Low'
    - 'UsageCategory_Medium'
    - 'UsageCategory_nan'
   