columns:
  - name: 'Fan'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 5.0
        max: 23.0
          

  - name: 'Refrigerator'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 18.0
        max: 23.0
          

  - name: 'AirConditioner'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 3.0
           

  - name: 'Television'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 3.0
        max: 22.0
      
           
  - name: 'Month'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 1
        max: 12
          

  - name: 'MonthlyHours'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 126
        max: 843
          
  - name: 'TariffRate'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 7.40
        max: 9.30             
                       
    name: 'ElectricityBill'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 1033.2
        max: 7793.4

    name: 'TotalApplianceHours'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 27.0
        max: 72.0

    name: 'UsageCategory_Low	'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0

    name: 'UsageCategory_Medium'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0       


  - name: 'City'
    type: 'string'
    constraints:
      - type: 'pattern'
        values:
          - 'Hyderabad'                                               
          - 'Vadodara'                 
          - 'Shimla'                                    
          - 'Mumbai'                           
          - 'Ratnagiri'                                     
          - 'New Delhi'                                    
          - 'Dahej'                           
          - 'Ahmedabad'                                                  
          - 'Noida'                                       
          - 'Nagpur'                          
          - 'Chennai'                               
          - 'Faridabad'                             
          - 'Kolkata '                                    
          - 'Pune'      
          - 'Gurgaon'                  
          - 'Navi Mumbai'                                        
          

  - name: 'Company'
    type: 'string'
    constraints:
      - type: 'enum'
        values:
          - 'Tata Power Company Ltd.'                         
          - 'NHPC'                  
          - 'Jyoti Structure'    
          - 'Power Grid Corp'               
          - 'Ratnagiri Gas and Power Pvt. Ltd. (RGPPL)'              
          - 'Adani Power Ltd.'
          - 'Kalpataru Power'
          - 'Orient Green'
          - 'Sterlite Power Transmission Ltd'
          - 'Neueon Towers / Sujana Towers Ltd.'
          - 'KEC International'
          - 'Indowind Energy'
          - 'Unitech Power Transmission Ltd.'
          - 'Bonfiglioli Transmission Pvt. Ltd'
          - 'SJVN Ltd.'
          - 'Maha Transco – Maharashtra State Electricity Transmission Co, Ltd.'
          - 'L&T Transmission & Distribution'
          - 'Guj Ind Power'
          - 'Torrent Power Ltd.'
          - 'Reliance Energy'
          - 'GE T&D India Limited'
          - 'NTPC Pvt. Ltd.'
          - 'KEC International'
          - 'Optibelt Power Transmission India Private Limited'
          - 'CESC'
          - 'Ringfeder Power Transmission India Pvt. Ltd.'
          - 'JSW Energy Ltd.'
          - 'Sunil Hitech Eng'
          - 'Toshiba Transmission & Distribution Systems (India) Pvt.'
          - 'Kalpataru Power'
          - 'Jaiprakash Power'
          - 'Bonfiglioli Transmission Pvt. Ltd.'
          - 'Optibelt Power Transmission India Private Limited'
          - 'TransRail Lighting'
          

  - name: 'Company_Toshiba Transmission & Distribution Systems (India) Pvt. Ltd.'
    type: 'integer'
    constraints:
      - type: 'enum'
        min: 0.0
        max: 1.0

  - name: 'Company_TransRail Lighting'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0

  - name: 'Company_Unitech Power Transmission Ltd'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0
          
 -  name: 'City_Chennai'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0 

    name: 'season_Summer'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0 

    name: 'season_Winter'
    type: 'integer'
    constraints:
      - type: 'range'
        min: 0.0
        max: 1.0 