artifacts_root: artifacts

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/validated_data.parquet
  random_state: 42
  target_col: 'ElectricityBill'
  numerical_cols:
    - 'Fan'
    - 'Refrigerator' 
    - 'AirConditioner'
    - 'Television' 
    - 'Month'
    - 'MonthlyHours' 
    - 'TariffRate'
    - 'ElectricityBill'
    - 'TotalApplianceHours'
  

  categorical_cols:
    - 'City'
    - 'season'
    - 'Company'